server:
  port: 5555

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: security
          uri: http://172.20.0.12:8189/
          predicates:
            - Path=/security/**
          filters:
            - StripPrefix=1
        - id: core
          uri: http://172.20.0.13:8189/
          predicates:
            - Path=/main/**
          filters:
            - StripPrefix=1
            - JwtAuthFilter

        - id: catch-all
          uri: no://op
          predicates:
            - Path=/**
          filters:
            - SetStatus=403

auth:
  server:
    url: http://172.20.0.12:8189/auth