spring:
  cloud:
    gateway:
      globalcors:
        enabled: true
        corsConfigurations:
          '[/**]':
            allowed-origins:
              - "http://5.129.246.42/"
            allowed-methods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
            allowed-headers:
              - "Content-Type"
              - "Authorization"
            allow-credentials: true
